services:
 db:
 container_name: <название любое>
image: postgres:15
environment:
POSTGRES_USER: admin
POSTGRES_PASSWORD: admin
POSTGRES_DB: db
PGDATA: /var/lib/postgresql/data
volumes:
- .postgres_data:/var/postgresql
ports:
- "5432:5432"

pgadmin:
container_name: <название любое>
image: dpage/pgadmin4:6
environment:
PGADMIN_DEFAULT_EMAIL: admin@natsmur.com
PGADMIN_DEFAULT_PASSWORD: admin
PGADMIN_LISTEN_ADDRESS: 0.0.0.0
volumes:
- .pgadmin-data:/var/pgadmin
ports:
- "8080:80"
